import Head from 'next/head'
import Selector from '../components/Selector'

import dynamic from 'next/dynamic'
import { Suspense } from 'react'

const DynamicScene = dynamic(() => import('../components/Scene'), {
  suspense: true,
})

export default function Home() {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='scene_container'>
        <Suspense fallback={<div>Loading...</div>}>
          <DynamicScene />
        </Suspense>
        <Selector />
      </main>
    </div>
  )
}
